Repository wrtnlabs/connectors, pull requests merged in 2024-07, with the labels that each got.

#152 OpenAI executor 실험
  src/api/structures/openapi/ISwagger.ts
  src/api/structures/openapi/ISwaggerComponents.ts
  src/api/structures/openapi/ISwaggerInfo.ts
  src/api/structures/openapi/ISwaggerRoute.ts
  src/api/structures/openapi/ISwaggerSchema.ts
  src/api/structures/openapi/ISwaggerSecurityScheme.ts
  src/api/utils/NestiaSimulator.ts
  src/api/utils/SwaggerTypeChecker.ts
  src/services/openai/IOpenAiDocument.ts
  src/services/openai/OpenAiConverter.ts
  src/services/openai/OpenAiFetcher.ts
Labels: enhancement

#153 Exact OpenAiFetcher
  src/services/openai/OpenAiFetcher.ts
Labels: bug, enhancement

#154 Add version.json
  packages/api/.gitignore
  src/executable/openai.ts
Labels: documentation

#157 OpenAI mode separation
  package-lock.json
  package.json
  packages/api/.gitignore
  src/executable/openai.ts
  src/services/openai/IOpenAiDocument.ts
  src/services/openai/OpenAiConverter.ts
  src/services/openai/OpenAiFetcher.ts
  website/build/swagger.js
Labels: documentation, enhancement

#169 Update version.yml
  .github/workflows/version.yml
Labels: enhancement

#173 Fix openai.json
  src/services/openai/OpenAiConverter.ts
Labels: documentation, enhancement

#176 Fix/figma and console error
  src/api/structures/connector/figma/IFigma.ts
  src/providers/connector/arxiv_search/ArxivSearchProvider.ts
  src/providers/connector/aws/AwsProvider.ts
  src/providers/connector/chatbot/ChatbotProvider.ts
  src/providers/connector/csv/CsvProvider.ts
  src/providers/connector/dall_e_3/DallE3Provider.ts
  src/providers/connector/daum/DaumProvider.ts
  src/providers/connector/excel/ExcelProvider.ts
  src/providers/connector/extract/KeywordExtractorProvider.ts
  src/providers/connector/gmail/GmailProvider.ts
  src/providers/connector/google_calendar/GoogleCalendarProvider.ts
  src/providers/connector/google_docs/GoogleDocsProvider.ts
  src/providers/connector/google_scholar/GoogleScholarProvider.ts
  src/providers/connector/google_sheet/GoogleSheetProvider.ts
  src/providers/connector/google_slides/GoogleSlidesProvider.ts
  src/providers/connector/hancell/HancellProvider.ts
  src/providers/connector/imweb/ImwebProvider.ts
  src/providers/connector/kakao_map/KakaoMapProvider.ts
  src/providers/connector/kakao_talk/KakaoTalkProvider.ts
  src/providers/connector/naver/NaverProvider.ts
  src/providers/connector/notion/NotionProvider.ts
  src/providers/connector/open_data/OpenDataProvider.ts
  src/providers/connector/prompt/PromptProvider.ts
  src/providers/connector/stable_diffusion_beta/StableDiffusionBetaProvider.ts
  src/providers/connector/sweet_tracker/SweetTrackerProvider.ts
  src/providers/figma/FigmaProvider.ts
  test/features/api/connector/figma/test_api_connector_figma.ts
Labels: Figma

#183 OpenAI schema separation to LLM and Human roles
  package-lock.json
  package.json
  src/executable/openai.ts
  src/services/openai/IOpenAiDocument.ts
  src/services/openai/OpenAiConverter.ts
  src/services/openai/OpenAiFetcher.ts
Labels: documentation

#187 Bump `@wrtnio/openai-function-schema` up
  package-lock.json
  package.json
Labels: documentation

#186 fix: kakao_navi response type
  src/api/functional/connector/kakao_navi/get_future_directions/index.ts
  src/api/structures/connector/kakao_navi/IKakaoNavi.ts
  src/controllers/connector/kakao_navi/KakaoNaviController.ts
  src/providers/connector/kakao_navi/KakaoNaviProvider.ts
  test/features/api/connector/kakao_navi/test_api_connector_kakao_navi.ts
Labels: kakao-navi

#196 Bump up dependencies
  package-lock.json
  package.json
Labels: enhancement

#209 Bump up `@nestia/sdk` for `OpenApi.IOperation.IParameter.title`.
  package-lock.json
  package.json
  packages/api/package.json
  test/index.ts
  test/inhouse.ts
  test/webpack.ts
Labels: documentation, enhancement

#195 Google Ads PR
  src/ConnectorGlobal.ts
  src/api/functional/connector/google_ads/ads/at_once/index.ts
  src/api/functional/connector/google_ads/ads/index.ts
  src/api/functional/connector/google_ads/campaign/index.ts
  src/api/functional/connector/google_ads/generateKeywordIdeas/index.ts
  src/api/functional/connector/google_ads/get_ads/index.ts
  src/api/functional/connector/google_ads/get_campaigns/index.ts
  src/api/functional/connector/google_ads/get_customers/index.ts
  src/api/functional/connector/google_ads/index.ts
  src/api/functional/connector/index.ts
  src/api/structures/connector/google_ads/IGoogleAds.ts
  src/api/structures/connector/kakao_talk/IKakaoTalk.ts
  src/controllers/connector/ConnectorModule.ts
  src/controllers/connector/google_ads/GoogleAdsController.ts
  src/controllers/connector/google_ads/GoogleAdsModule.ts
  src/providers/connector/google_ads/GoogleAdsProvider.ts
  src/providers/connector/google_slides/GoogleSlidesProvider.ts
  src/providers/internal/google/GoogleProvider.ts
  src/utils/TypedSplit.ts
  src/utils/retry.ts
  src/utils/types/ArrayType.ts
  src/utils/types/DeepStrictMerge.ts
  src/utils/types/Rename.ts
  src/utils/types/SelectedColumns.ts
  src/utils/types/SnakeToCamelCaseObject.ts
  src/utils/types/StringType.ts
  src/utils/types/Typing.ts
  test/features/api/connector/google_ads/test_api_connector_google_ads_create_ad.ts
  test/features/api/connector/google_ads/test_api_connector_google_ads_create_ad_at_once.ts
  test/features/api/connector/google_ads/test_api_connector_google_ads_create_campaign.ts
  test/features/api/connector/google_ads/test_api_connector_google_ads_generate_keyword_ideas.ts
  test/features/api/connector/google_ads/test_api_connector_google_ads_get_ads.ts
  test/features/api/connector/google_ads/test_api_connector_google_ads_get_campaigns.ts
  test/features/api/connector/google_ads/test_api_connector_google_ads_get_clients.ts
Labels: Google Ads

#216 OpenAPI version up for title specification
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: documentation

#253 Change type of `RagController.generate()`
  src/controllers/connector/rag/RagController.ts
Labels: enhancement

#266 기상청 데이터에 대한 격자 좌표 대응 및 주요 도시 테스트 추가
  src/api/structures/connector/open_data/IOpenData.ts
  src/controllers/connector/open_data/OpenDataController.ts
  src/providers/connector/open_data/OpenDataProvider.ts
  test/features/api/connector/open_data/test_api_connector_open_data.ts
  test/features/api/connector/open_data/test_api_connector_open_data_short_term_forecast.ts
Labels: Open-Data

#286 Bump up dependencies
  package-lock.json
  package.json
Labels: documentation

#288 Complete translator
  packages/api/swagger.korean.json
  src/executable/translate.ts
Labels: documentation, enhancement
